### ISSUE TITLE
Workflow addon upload

### ISSUE THREAD

**Issue by shukari** [nk3nny/LambsDanger#141]
https://github.com/nk3nny/LambsDanger/blob/043761e58b995c42889aa72ac404414a1af0ffbb/.github/workflows/main.yml#L46-L53

```
HEMTT 0.7.6-51deaa6
Environment: ci

warning: Unable to use binarize.exe on non-windows systems
    Files will be packed as is
♻️ Clean       
🔍 Checks      
Check `!version_set`
Setting version
🚧 Prebuild    
📝 Build       
PostBuild `!version_unset`
Unsetting version
⭐ Release     
⭐ Sign        
ReleaseBuild `@zip @LambsDanger_2_4_4`
Archiving @LambsDanger_2_4_4.zip
```

```
Run actions/upload-artifact@master0s
##[warning]No files were found for the provided path: releases/@LambsDanger.zip. No artifacts will be uploaded.
```

Change to that?
```
      - uses: actions/upload-artifact@master
        with:
          name: '@LambsDanger'
          path: 'releases/@LambsDanger*.zip'
```
